---
tools:
- name: githubactions
  version: 0.0.1
  options:
    owner: ironcore864
    repo: go-hello-http
    language:
      name: go
      version: "1.17"
    branch: master
- name: argocd
  version: 0.0.1
  options:
    repo:
      name: argo
      url: https://argoproj.github.io/argo-helm
    chart:
      name: argo/argo-cd
      release_name: argocd
      namespace: argocd
      create_namespace: False

