config:
  state: # state config, backend can be local, s3 or k8s
    backend: local
    options:
      stateFile: devstream.state

vars:
  defaultBranch: main
  githubUsername: daniel-hutao
  repoName: dtm-test-go
  jiraID: merico
  jiraUserEmail: tao.hu@merico.dev
  jiraProjectKey: DT
  dockerhubUsername: exploitht
  argocdNameSpace: argocd

tools:
- name: repo-scaffolding
  instanceID: golang-github
  options:
    destinationRepo:
      owner: [[ githubUsername ]]
      name: [[ repoName ]]
      branch: [[ defaultBranch ]]
      scmType: github
    sourceRepo:
      org: devstream-io
      name: dtm-scaffolding-golang
      scmType: github
    vars:
      imageRepo: "[[ dockerhubUsername ]]/[[ repoName ]]"
- name: jira-github-integ
  instanceID: default
  dependsOn: [ "repo-scaffolding.golang-github" ]
  options:
    owner: [[ githubUsername ]]
    repo: [[ repoName ]]
    jiraBaseUrl: https://[[ jiraID ]].atlassian.net
    jiraUserEmail: [[ jiraUserEmail ]]
    jiraProjectKey: [[ jiraProjectKey ]]
    branch: main
- name: github-actions
  instanceID: default
  dependsOn: [ "repo-scaffolding.golang-github" ]
  options:
    scm:
      owner: ${{repo-scaffolding.golang-github.outputs.owner}}
      name: ${{repo-scaffolding.golang-github.outputs.repo}}
      branch: [[ defaultBranch ]]
      scmType: github
    pipeline:
      configLocation: https://raw.githubusercontent.com/devstream-io/ci-template/main/github-actions/workflows/main.yml
      language:
        name: go
        framework: gin
      imageRepo:
        user: [[ dockerhubUsername ]]
- name: helm-installer
  instanceID: argocd
- name: argocdapp
  instanceID: default
  dependsOn: ["helm-installer.argocd", "repo-scaffolding.golang-github"]
  options:
    app:
      name: ${{repo-scaffolding.golang-github.outputs.repo}}
      namespace: [[ argocdNameSpace ]]
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      valuefile: values.yaml
      path: helm/${{repo-scaffolding.golang-github.outputs.repo}}
      repoURL: ${{repo-scaffolding.golang-github.outputs.repoURL}}
