config:
  state:
    backend: local
    options:
      stateFile: devstream.state

tools:
- name: repo-scaffolding
  instanceID: golang-github
  options:
    destinationRepo:
      owner: YOUR_GITHUB_USERNAME_CASE_SENSITIVE
      org: ""
      repo: go-webapp-devstream-demo
      branch: main
      repoType: github
    sourceRepo:
      org: devstream-io
      repo: dtm-scaffolding-golang
      repoType: github
    vars:
      imageRepo: YOUR_DOCKER_USERNAME/go-webapp-devstream-demo
- name: githubactions-golang
  instanceID: default
  dependsOn: ["repo-scaffolding.golang-github"]
  options:
    owner: YOUR_GITHUB_USERNAME_CASE_SENSITIVE
    repo: go-webapp-devstream-demo
    language:
      name: go
      version: "1.18"
    branch: main
    build:
      enable: True
    test:
      enable: True
      coverage:
        enable: True
    docker:
      enable: False
