name: Cloudflare IP Monitor

on:
  schedule:
    - cron: 0 12 * * * # every day at 12:00

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check IPs
        run: |
          cd hack/cf-ip-monitor || exit
          bash check.sh
        shell: bash
      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        if: env.CHANGED == 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: hack/cf-ip-monitor/ISSUE_TEMPLATE.md
