name: Cloudflare IP Monitor

on:
  schedule:
    - cron: 0 12 * * * # every day at 12:00

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check IPs
        run: |
          cd hack/cf-ip-monitor || exit
          curl -sL https://www.cloudflare.com/ips-v4 | grep -v '^$' >ips-v4
          cat ips-v4
          if git status --porcelain | grep -q "^ M";then
            echo "ips-v4 changed"
            echo "CHANGED=1" >> $GITHUB_ENV
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add ips-v4
            git commit -m "chore: ips-v4 changed"
            git push
          else
            echo "ips-v4 not changed"
          fi
      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        if: env.CHANGED == 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: hack/cf-ip-monitor/ISSUE_TEMPLATE.md
