name: update download.sh

on:
  push:
    branches: [ main ]
    paths:
      - hack/install.sh
  workflow_dispatch:

jobs:
    update-download-script:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-1
        - name: Update download.sh
          run: aws s3 cp hack/install/download.sh s3://download.devstream.io/download.sh --acl public-read
