name: ut on linux
on:
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }}-${{ runner.arch }} server hosted by GitHub!"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang env
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: make build -j8
      - name: Test
        run: go test -v ./...
